### ISSUE TITLE
Evaluation script missing

### ISSUE THREAD

**Issue by waylonli** [Harryx2019/CI-STHPAN#1]
Hi Hongjie, I am trying to cite your paper and run the experiments to reproduce the results. The pretraining and finetuning works well but I couldn't find the evaluation script which gets the IRR and SR results? Also, is it possible to get some guidance about how to use those pretrained models on the netdisk? There are many folders in the zip file which makes it a bit confusing.

Appreciate to any help!

**Comment by Harryx2019** [comment]
Thanks for the interest in our research! The evaluation code at:
supervised: CI-STHPAN_supervised/utils/metrics.py
pretrain: CI-STHPAN_self_supervised/src/metrics.py

The filename of a model consists of different hyperparameters, and the corresponding model can be selected by referring to the definition of each parameter in CI-STHPAN_supervised/run_longExp.py.

**Comment by Harryx2019** [comment]
> Hi Hongjie, I am trying to cite your paper and run the experiments to reproduce the results. The pretraining and finetuning works well but I couldn't find the evaluation script which gets the IRR and SR results? Also, is it possible to get some guidance about how to use those pretrained models on the netdisk? There are many folders in the zip file which makes it a bit confusing.
> 
> Appreciate to any help!


Thanks for the interest in our research! The evaluation code at:
supervised: CI-STHPAN_supervised/utils/metrics.py
pretrain: CI-STHPAN_self_supervised/src/metrics.py

The filename of a model consists of different hyperparameters, and the corresponding model can be selected by referring to the definition of each parameter in CI-STHPAN_supervised/run_longExp.py.
