### ISSUE TITLE
通道独立与MS模式

### ISSUE THREAD

**Issue by nnstake** [Harryx2019/CI-STHPAN#3]
既然模型采用了PatchTST那样的通道独立，在监督学习中又用了MS（多变量预测单变量模式），不是相当于只用了目标通道（Close）做了个单变量预测吗，既然如此完全没必要使用其他四个通道啊

**Comment by Harryx2019** [comment]
感谢对我们研究工作的关注！是的，模型最终只在close维度上进行预测，我们后续会实验对比单变量预测和MS预测的区别。
